User.create(username: "ihunt123", password: "bowhunt")
User.create(username: "targetguy", password: "long-range")
Bow.create(name: "Hunting", arrow_head: "Mechanical Broadhead", arrow_shaft: "300", arrow_rest: "Whisker Biscuit", front_sight: "5", peep_sight: "1/4", model: "Hoyt Torrex", quiver: "Mounted 4", release: "Thumb", stabilizer: "6", user_id: 1)
Bow.create(name: "Competition", arrow_head: "Field Tip", arrow_shaft: "350", arrow_rest: "Drop Away", front_sight: "3", peep_sight: "3/16", model: "Mathews VXR", quiver: "Hip 3", release: "Wrist", stabilizer: "12", user_id: 2)

# ArrowRest.create(type: "Whisker Biscuit")
# ArrowRest.create(type: "Drop Away")
# ArrowHead.create(type: "Field Tip")
# ArrowHead.create(type: "Fixed Broadhead")
# ArrowHead.create(type: "Mechanical Broadhead")
# ArrowShaft.create(type: 300)
# ArrowShaft.create(type: 350)
# FrontSight.create(type: 3)
# FrontSight.create(type: 4)
# FrontSight.create(type: 5)
# PeepSight.create(type: "1/4")
# PeepSight.create(type: "3/16")
# Model.create(type: "Hoyt Torrex")
# Model.create(type: "Bear Divergent")
# Quiver.create(type: "Mounted 4")
# Quiver.create(type: "Hip 3")
# Release.create(type: "Wrist")
# Release.create(type: "Thumb")
# Stabilizer.create(type: 6)
# Stabilizer.create(type: 8)